name: Lint Code Base

on: push

jobs:
  super-lint:
    name: Lint Code Base
    runs-on: ubuntu-lastest

    env:
      PYTHON: '3.7'

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      -name: Lint Code Base
       uses: github/super-linter@v4
       env:
        DEFAULT_BRANCH: master
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        VALIDATE_PYTHON_BLACK: true
        VALIDATE_PYTHON_FLAKEB: true